# docker-compose.yml
services:
    postgres:
        # 使用一个轻量且稳定的 PostgreSQL 15 镜像
        image: postgres:15-alpine
        # 容器总是尝试重启，除非被手动停止
        restart: always
        # 在这里设置你的数据库用户名、密码和数据库名
        environment:
            POSTGRES_USER: Andrews
            POSTGRES_PASSWORD: 6846715ABC_t
            POSTGRES_DB: tinyroom_db
        ports:
            # 将容器的 5432 端口映射到你电脑的 5432 端口
            # 格式: 'HOST_PORT:CONTAINER_PORT'
            - "5432:5432"
        volumes:
            # 将数据库数据持久化到本地的一个文件夹中
            # 这样即使删除和重建容器，数据也不会丢失
            - ./postgres_data:/var/lib/postgresql/data

volumes:
    # 声明一个数据卷，由 Docker 管理
    postgres_data:
