name: Sync Obsidian Vault

on:
    workflow_dispatch: # Allows manual triggering
    schedule:
        - cron: "0 * * * *" # Runs every hour

jobs:
    sync:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout Target Repo
              uses: actions/checkout@v4
              with:
                  # This is the token for the repo the action is running in (Tiny-Room)
                  # It's automatically provided by GitHub Actions
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Clone Obsidian Vault
              uses: actions/checkout@v4
              with:
                  repository: ${{ secrets.OBSIDIAN_VAULT_URL }}
                  token: ${{ secrets.OBSIDIAN_VAULT_TOKEN }}
                  path: ".obsidian_vault"

            - name: Sync Published Notes
              run: |
                  # Ensure the target directory exists
                  mkdir -p posts

                  # Clear the posts directory to handle file deletions
                  rm -rf posts/*

                  # Find notes with "status: publish" in frontmatter and copy them
                  # Using grep to be efficient and avoid complex parsing
                  grep -r -l --include='*.md' "status: publish" .obsidian_vault | while read -r file;
                  do
                    # Copy the found file to the posts directory
                    cp "$file" posts/
                  done

            - name: Commit and Push Changes
              run: |
                  git config --global user.name 'github-actions[bot]'
                  git config --global user.email 'github-actions[bot]@users.noreply.github.com'
                  git add posts/
                  # Check if there are changes to commit
                  if git diff --staged --quiet; then
                    echo "No changes to commit."
                  else
                    git commit -m "docs: sync published notes from obsidian vault"
                    git push
                  fi
